### ISSUE TITLE
Unable to restore a course or category - from the tab admin->courses->categories->Restore Remote Courses in Category

### ISSUE THREAD

**Issue by Nitr0z** [UNIMOODLE/moodle-local_coursetransfer#25]
![image](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/48621976/6a73baca-7485-4637-9e62-6e985a0b442b)

**Comment by Nitr0z** [comment]
the red error means in English: A name is required for the category

**Comment by xpazv** [comment]
Fixed in latest version available.

**Comment by Nitr0z** [comment]
We still have the error, on the latest version/code available. I tried on few plateform, in few version 4.0 to 4.4.

**Comment by Nitr0z** [comment]
![image](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/48621976/795c5d38-fb69-4e0b-a248-6f7a017330f7)
![image](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/48621976/ef2b4b92-2ed6-4ee9-b3d3-231f3487b488)

**Comment by xpazv** [comment]
We will review it.

**Comment by xpazv** [comment]
Fixed in latest version.
